[package]
name = "wings-reverse"
version = "0.1.0"
authors = ["Petri Lehtinen <petri@digip.org>"]
description = "Convert Wings 1.40 data files to more accessible formats"
edition = "2021"

[dependencies]
clap = { version = "3.2.22", features = ["derive"] }
image = "0.24.3"
nom = "7.1.1"
